baguio = input('Digite algo: ')
print(type(baguio))
print(f'É alfanumérico? {baguio.isalnum()}')
print(f'É número? {baguio.isnumeric()}')
print(f'É letra? {baguio.isalpha()}')
print(f'É espaço? {baguio.isspace()}')
print(f'É imprimivel? {baguio.isprintable()}')
print(f'É ASCII? {baguio.isascii()}')
print(f'É decimal? {baguio.isdecimal()}')
print(f'É indentificador? {baguio.isidentifier()}')
print(f'É digito? {baguio.isdigit()}')
print(f'Está minúsculo? {baguio.islower()}')
print(f'Está maiúsculo? {baguio.isupper()}')
print(f'Está em formato de titúlo? {baguio.istitle()}')
