num = int(input('Digite um número: '))
print('   TABUADA')
print(f'{num:>3} x 0 = {num * 0:>3}')
print(f'{num:>3} x 1 = {num * 1:>3}')
print(f'{num:>3} x 2 = {num * 2:>3}')
print(f'{num:>3} x 3 = {num * 3:>3}')
print(f'{num:>3} x 4 = {num * 4:>3}')
print(f'{num:>3} x 5 = {num * 5:>3}')
print(f'{num:>3} x 6 = {num * 6:>3}')
print(f'{num:>3} x 7 = {num * 7:>3}')
print(f'{num:>3} x 8 = {num * 8:>3}')
print(f'{num:>3} x 9 = {num * 9:>3}')
